### ISSUE TITLE
Add a server on a NetScaler

### ISSUE THREAD

**Issue by hbombonato** [RamblingCookieMonster/Citrix.NetScaler#2]
Provide the creation a server on a netscaler, with parameters -Address,  hostname ipaddress login and password to user of a service.

 Add-NSserverconfig [-Address <String>] [[-vname] <String>] [[-hostip] <String>] [[-srvuser] <String>] [[-srvpass] <String>]  [-Raw] [-AllowHTTPAuth] [-TrustAllCertsPolicy <Boolean>] [<CommonParameters>]

**Comment by RamblingCookieMonster** [comment]
Closing this out - the project is pretty much dead, check out modules [like Brandon's](https://github.com/devblackops/NetScaler) - Cheers!
