### ISSUE TITLE
Add lbvservers on a NetScaler

### ISSUE THREAD

**Issue by hbombonato** [RamblingCookieMonster/Citrix.NetScaler#4]
Provide the creation a lbvservers on a netscaler, with parameters [-Address ] [[-lbname] ] [[-lbservice] ] [[-lbvipaddress] ] [[-lbport] ] [[-lbmethod] ] [[-lbenv]] [[-srvuser] ] [[-srvpass] ] [[-comment]] [-Raw] [-AllowHTTPAuth] [-TrustAllCertsPolicy ], also i suggest to compose lbname the mask VIP_$lbname_$lbenv_$lbport(VIP_product_QA_80)

Add-NSconfiglbvserver -Address CTX-NS-01 -lbname product -lbservice HTTP|HTTPS -lbvipaddress 1.1.2.1 -lbport 80 -lbmethod "roundrobin|lastcon" -lbenv "environment QA|DEV|PROD" -srvuser -comment "comment it" -AllowHTTPAuth

**Comment by RamblingCookieMonster** [comment]
Closing this out - the project is pretty much dead, check out modules [like Brandon's](https://github.com/devblackops/NetScaler) - Cheers!
